spring:
  profiles:
    active: database
mybatis:
  # 标注待解析的mapper的xml文件位置
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # org.apache.ibatis.logging.stdout.StdOutImpl
    # org.apache.ibatis.logging.slf4j.Slf4jImpl
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
---
spring:
  emily:
    logback:
      enabled: true
      enable-size-and-time-rolling-policy: true
      #common-pattern: "[%d{yyyy-MM-dd HH:mm:ss.SSS}] [%thread] [%p (%file:%line\\)] : %msg%n"
      # [%d{yyyy-MM-dd HH:mm:ss.SSS}] [%thread] [%-5level] [%d %p (%file:%line\\)] : %msg%n
      level: trace
---



